# Generated by Django 5.1.1 on 2024-09-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_chartbar_bucket_alter_chartbar_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('travel', 'Travel'), ('leisure', 'Leisure'), ('work', 'Work')], max_length=10),
        ),
    ]
